### ISSUE TITLE
Build allows warnings

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-samples-rs#13]
The new webview2 samples (@wravery) builds with warnings. I would have expected the GitHub build to block that but it passed the build. Need to figure out how to ensure that warnings block the build.

**Comment by wravery** [comment]
Makes sense, it seems like it should block for that.

Here's the warning in question from the logs for reference:
```
   Compiling callback_macros v0.0.0 (D:\a\windows-samples-rs\windows-samples-rs\webview2_win32\callback-macros)
warning: field is never read: `struct_token`
  --> callback-macros\src\lib.rs:39:5
   |
39 |     pub struct_token: Token![struct],
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: 1 warning emitted
```
The weird thing is I don't get the same error locally with a clean build, maybe because I'm on stable instead of nightly. I think I probably made that field `pub` for that warning originally, although I've had this macro crate in my local tests for a while, so I'm not sure.

**Comment by kennykerr** [comment]
Yes, the warning is new in the nightly builds. I used nightly locally. The GitHub build tests both nightly and stable.
